name: Pana

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pana:
    name: Pub Points
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable
          flutter-version-file: .fvmrc
          cache: true

      - name: Install dependencies
        run: flutter pub get --enforce-lockfile

      - name: Install pana
        run: dart pub global activate pana

      - name: Run pana
        run: dart pub global run pana --no-warning --exit-code-threshold 30 packages/formbricks_flutter
